version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/store-app"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    allow:
      - dependency-name: "org.apache.commons:commons-lang3"
      - dependency-name: "org.apache.commons:commons-collections4"
      - dependency-name: "org.apache.commons:commons-logging"
      - dependency-name: "org.apache.commons:commons-email"
      - dependency-name: "org.apache.commons:commons-pool2"
      - dependency-name: "org.apache.commons:commons-dbcp2"
      - dependency-name: "org.apache.commons:commons-net"
      - dependency-name: "commons-fileupload:commons-fileupload"
      - dependency-name: "org.apache.httpcomponents:httpclient"
      - dependency-name: "org.apache.logging.log4j:log4j-core"
      - dependency-name: "org.springframework:spring-core"
      - dependency-name: "org.springframework:spring-web"
      - dependency-name: "com.fasterxml.jackson.core:jackson-databind"
      - dependency-name: "org.webjars:jquery"
